# Generated by Django 5.1.3 on 2024-11-16 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAStudio', '0003_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2024, 11, 16, 15, 5, 20, 663659, tzinfo=datetime.timezone.utc)),
        ),
    ]
