# Generated by Django 5.1.3 on 2024-11-16 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAStudio', '0004_alter_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2024, 11, 16, 17, 18, 10, 182447, tzinfo=datetime.timezone.utc)),
        ),
    ]
