# Generated by Django 5.1.3 on 2024-11-16 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAStudio', '0007_alter_post_file_alter_post_image_alter_post_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2024, 11, 16, 18, 6, 45, 664979, tzinfo=datetime.timezone.utc)),
        ),
    ]
