# Generated by Django 4.2.16 on 2024-11-21 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAStudio', '0015_rename_profile_userprofile_alter_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='requested_service',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2024, 11, 21, 17, 30, 22, 641561)),
        ),
    ]
