# Generated by Django 5.1.3 on 2024-11-23 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAStudio', '0016_userprofile_requested_service_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2024, 11, 23, 20, 51, 9, 416299)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='requested_service',
            field=models.CharField(max_length=20),
        ),
    ]
