# Generated by Django 5.1.3 on 2024-11-23 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAStudio', '0017_alter_post_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2024, 11, 23, 21, 42, 9, 496458)),
        ),
    ]
