# Generated by Django 5.1.3 on 2024-11-25 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HAStudio', '0020_report_alter_userprofile_requested_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Reports',
        ),
    ]
